# Dockerfile: MongoDB for Learnsphere Dexplorer service
FROM ubuntu:18.04

MAINTAINER Steven Dang "stevenda@cs.cmu.edu"


RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10 && \
   echo 'deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen' | sudo tee /etc/apt/sources.list.d/mongodb.list && \
      apt-get update && \
         apt-get install -y mongodb-org

# ADD mongod.conf /etc/mongod.conf

EXPOSE 23456
USER mongodb

VOLUME ["/data/db"]
WORKDIR /data

ENTRYPOINT ["/usr/bin/mongod", "--config", "/etc/mongod.conf", "--port", "23456"]
CMD ["--quiet"]


