FROM nginx

COPY nginx.conf /etc/nginx/nginx.conf
COPY reverse_proxy.conf.template /etc/nginx/conf.d/reverse_proxy.conf.template
RUN mkdir /app
COPY start.sh /app/
RUN chmod 777 /app/start.sh

CMD /bin/bash -c /app/start.sh
