kind: pipeline:
name: default

  steps:
    - name: backend
      image: plugins/docker 
      settings:
          username: 
            from_secret: d3m_username
          password: 
            from_secret: d3m_password
          repo: gitlab.datadrivendiscovery.org/sdang/cmu-ta3
          registry: registry.datadrivendiscovery.org/sdang/cmu-ta3 
